### ISSUE TITLE
Permission to use this template / App 

### ISSUE THREAD

**Issue by mhadaily** [esentis/Flutter-Halloween-UI#2]
Hey, 

I came across this theme, and I wonder if you will allow me to use this theme for a community project. You can also join me to help create this project if you want. I will be happy to share more information. You can find me on https://twitter.com/mhadaily or https://github.com/mhadaily/, https://www.linkedin.com/in/mhadaily/

Let me know what you think.

**Comment by esentis** [comment]
That would be my pleasure, do as you please <3

**Comment by mhadaily** [comment]
Perfect, thank you. If you are on Twitter, let me know what's your handler is so, when I announce the project, I will shout it out to you too.

**Comment by esentis** [comment]
> Perfect, thank you. If you are on Twitter, let me know what's your handler is so, when I announce the project, I will shout it out to you too.

Nuh, I'm not at Twitter. Though you could also share it on Ln where I'm active :)
